.gitignore, d2.config.js
https://jira.dhis2.org/browse/TECH-847
=> feat: enable pwa

i18n/en.pot, package.json, src/data-workspace/category-combo-table.js, src/data-workspace/category-combo-table.module.css, src/data-workspace/data-entry-cell.js, src/data-workspace/data-workspace.js, src/data-workspace/section.js, yarn.lock
=> feat: add entry cells (wip)

src/context-selection/attribute-option-combo-selector-bar-item/attribute-option-combo-selector-bar-item.js, src/context-selection/context-selection/context-selection.js, src/context-selection/data-set-selector-bar-item/data-set-selector-bar-item.js, src/context-selection/org-unit-selector-bar-item/get-filtered-org-unit-paths.js, src/context-selection/org-unit-selector-bar-item/org-unit-selector-bar-item.js, src/context-selection/org-unit-selector-bar-item/use-org-unit-paths-by-name.js, src/context-selection/section-filter-selector-bar-item/section-filter-selector-bar-item.js
For some reason I added an empty feature file which breaks the tests.. So removing it
(and fixing the prettier errors.. hope that won't cause too many merge conflicts :sweat_smile: 
OT: @varl Could we make the lint checks in the GH workflows only check changed files?
=> chore(cypress): remove empty feature file

src/data-workspace/data-workspace.module.css, src/data-workspace/entry-form.js, src/data-workspace/entry-form.module.css, src/data-workspace/section.js, src/data-workspace/section.module.css
Adds spacing between entry form elements (filter input and tables) and fixes some section header styles, including a too-short filter input
=> feat: section styles

src/data-workspace/data-entry-cell/data-entry-cell.js, src/data-workspace/data-entry-cell/data-entry-cell.module.css, src/data-workspace/data-entry-cell/validation-tooltip.js, src/data-workspace/data-workspace.module.css
Adds a tooltip to cells when the type of the value in the cell does not match the data element's `valueType`, as described in the [design specifications](https://docs.google.com/document/d/1NDMM-FAGCdM41n8ShnQuS6snvKvdSWNW-rky23cio_I/edit#heading=h.6ajrvb1c1ck)
=> feat: invalid cell tooltip

src/metadata/selectors.test.js
Adds tests for the metadata selectors. Based on development.
=> test: add selector tests

src/data-workspace/use-data-value-mutation/use-api-error.js, src/data-workspace/use-data-value-mutation/use-data-value-mutation.js
Closes [TECH-1121 ](https://dhis2.atlassian.net/browse/TECH-1121).
https://user-images.githubusercontent.com/1014725/175250079-299e64c1-259e-4b0f-b45e-2fbee24e80b9.mov
=> feat: handle dataset lock errors on mutation

src/data-workspace/data-details-sidebar/basic-information.js, src/data-workspace/data-details-sidebar/basic-information.test.js, src/data-workspace/data-entry-cell/entry-field-input.js
Closes [TECH-1220](https://dhis2.atlassian.net/browse/TECH-1220)
**Changes in this PR**
- Fixes the issue where date and user are displayed as null
- Also fixes an issue with the time not being displayed correctly  when the user is in a zone other than UTC
- Updates to tests
| Before | After |
| --- | -- |
| <img width="387" alt="image" src="https://user-images.githubusercontent.com/1014725/176402715-76790c96-7ba0-4c17-9ece-527e70ece68b.png"> | <img width="419" alt="image" src="https://user-images.githubusercontent.com/1014725/176402220-b7d4065f-6f86-4580-9126-164566196af2.png"> |
=> fix: display last updated date in basic info correctly

src/context-selection/use-context-selection/use-context-selection.js
closes [TECH-1226](https://dhis2.atlassian.net/browse/TECH-1226)
| Before | After |
| --- | --- |
| ![right-panel-hide-before](https://user-images.githubusercontent.com/1014725/176660698-30d77949-c1b6-404a-986d-055c7d325e2f.gif) | ![right-panel-hide-after](https://user-images.githubusercontent.com/1014725/176660723-c3f9ecb6-cd34-4b5c-80fc-9117cf9cc15f.gif) |
=> fix: hide right hand panel when context is cleared

src/data-workspace/inputs/generic-input.js
Fixes [TECH-1232](https://dhis2.atlassian.net/browse/TECH-1232)
=> fix: ensure empty values are not synced

src/data-workspace/validation/use-validation-result.js, src/data-workspace/validation/validation-comments-violations.js, src/data-workspace/validation/validation-comments-violations.module.css, src/data-workspace/validation/validation-results-sidebar.js
implements [TECH-1276](https://dhis2.atlassian.net/browse/TECH-1276)
**Note**: this is a temporary UI until we have design specs provided from @cooper-joe
=> feat: display validation comments violations

src/data-workspace/data-entry-cell/entry-field-input.js, src/data-workspace/entry-form.js, src/data-workspace/validation/validation-results-sidebar.js, src/data-workspace/validation/validation-results-sidebar.module.css, src/right-hand-panel/right-hand-panel-context.js, src/right-hand-panel/right-hand-panel-provider.js
implements [TECH-1275](https://dhis2.atlassian.net/browse/TECH-1275)
Show notification when the form has changed since running validation
=> feat: show notification when form has changed after last validation run

src/bottom-bar/data-item-bar.js
Fixes incorrect "Hide details" text when validation/help menu is open https://dhis2.atlassian.net/browse/TECH-1313
=> fix(bottom bar): correct hide/view details text

src/context-selection/options/options.js
Hides print options when non are selected https://dhis2.atlassian.net/browse/TECH-1333
=> fix(options menu): hide print options if no form is selected

src/data-workspace/default-form.js, src/shared/metadata/selectors.js, src/shared/metadata/selectors.test.js
Jira ticket: [TECH-1318](https://dhis2.atlassian.net/browse/TECH-1318)
Have data elements display alphabetical order by displayFormName on default forms
=> fix: default form prop order

src/app/app-wrapper.js, src/context-selection/contextual-help-sidebar/cell.js, src/context-selection/contextual-help-sidebar/cell.module.css, src/data-workspace/data-details-sidebar/comment.js, src/data-workspace/data-entry-cell/data-entry-cell.module.css, src/data-workspace/data-entry-cell/inner-wrapper.js, src/data-workspace/data-workspace.js, src/data-workspace/has-comment/has-comment-context.js, src/data-workspace/has-comment/has-comment-provider.js, src/data-workspace/has-comment/has-comment-provider.test.js, src/shared/use-data-value-set/use-data-value-set.js
It took me a while to find a somewhat suitable way to introduce this. Therefore I have left some comments in the PR to explain some of the quirks I encountered.
The fact that currently POSTing values, comments, etc. for a dataset with an AOC is broken, also affects this feature. You can test datasets with just a default AOC. Custom forms work too.
=> feat: show grey triangle when fields have a comment

i18n/en.pot, src/data-workspace/inputs/generic-input.js
Jira: [TECH-1246](https://dhis2.atlassian.net/browse/TECH-1246)
Adds in a formatting function onBlur on the general input that deals with values like..
- `.123` converting to `0.123`
- `0.` or `123.` converting to `0` or `123` respectfully
-  `000.123` converting to `0.123`
This specifically does the format for all Number types
=> feat: add formatting functionality for dealing with leading zeros and decimal places

README.md
https://dhis2-data-entry.netlify.app
=> docs: add link to development demo

src/app/app-wrapper.js
I managed to push this override... Sorry about that!
=> fix: tanstack query devtools

src/data-workspace/data-entry-cell/data-entry-cell.module.css
This PR makes a minor adjustment to the colors for synced cells. This change is a result of UX testing for different monitors/setups.
=> fix: adjust synced cell style

src/custom-forms/use-custom-forms-prefetch.js
- Already implemented
- Already implemented
- Already implemented
=> feat: notify user about failures of critical requests

src/data-workspace/filter-field.js
This PR fixes [DHIS2-13962](https://dhis2.atlassian.net/browse/DHIS2-13962), adjusts global filter field to use size `dense`.
=> fix: global filter field size

src/data-workspace/filter-field.js
https://dhis2.atlassian.net/browse/DHIS2-13963
=> fix(filter-field): hide clear-button when no filter

src/context-selection/org-unit-selector-bar-item/use-offline-levels.js, src/context-selection/org-unit-selector-bar-item/use-prefetched-organisation-units.js
Fixes [DHIS2-13976](https://dhis2.atlassian.net/browse/DHIS2-13976)
=> fix: ensure offline units are fetched correctly for users deep in the hierarchy

.github/workflows/dhis2-netlify-deploy-branch.yml
This will deploy any branches specified under line 14 as `{branch name}--{app name on netlify}.netlify.app` for each push. In this case that would be for development.
=> ci(netlify): add netlify branch deploy action

src/context-selection/context-selection/use-should-hide-clear-button.js
Fixes [DHIS2-14039](https://dhis2.atlassian.net/browse/DHIS2-14039) (Clicking 'Clear selections' does not reset dataset if only dataset is selected)
=> fix: clear selections with only dataset [DHIS2-14039]

.github/workflows/dhis2-netlify-deploy-branch.yml, .github/workflows/dhis2-netlify-deploy-pr.yml, .github/workflows/dhis2-netlify-deploy-production.yml
Testing out the changes made in https://github.com/dhis2/workflows/pull/37, just to doublecheck that it all works.
=> ci(netlify): update actions to latest versions

src/shared/date/use-server-time-offset.js, src/shared/stores/entry-form-store.test.js, src/shared/stores/get-cell-id.test.js, src/shared/stores/highlighted-field-store.js, src/shared/stores/highlighted-field-store.test.js, src/shared/stores/sync-errors-store.test.js, src/shared/stores/unsaved-data-store.js, src/shared/stores/unsaved-data-store.test.js, src/shared/stores/validation-store.test.js
Closes [DHIS2-14284](https://dhis2.atlassian.net/browse/DHIS2-14284)
Adds jest tests for all zustand stores
=> test: cover stores with tests (and fix some minor issues)

cypress/integration/context-selection/period.feature
This is only a temporary fix so other work in unblocked.
I'm working on a proper fix, but it takes more time than expected.
=> chore(cypress): disable broken tests temporarily

package.json, yarn.lock
This PR updates UI to the latest version in order to get the improvements to the `OrganisationUnitTree` component.
=> chore: update ui, app-runtime

src/shared/completion/use-set-form-completion-mutation.js, src/shared/completion/use-set-form-completion-mutation.test.js
Fixes [DHIS2-14378](https://dhis2.atlassian.net/browse/DHIS2-14378)
PR title has `fix` as there's a fix-commit
[DHIS2-14378]: https://dhis2.atlassian.net/browse/DHIS2-14378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: cover useSetFormCompletionMutation with tests

src/shared/validation/use-imperative-validate.test.js
Fixes [DHIS2-14385](https://dhis2.atlassian.net/browse/DHIS2-14385)
Blocked by #315 
[DHIS2-14385]: https://dhis2.atlassian.net/browse/DHIS2-14385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: cover useImperativeValidate with tests

src/data-workspace/section-form/section.js, src/shared/metadata/selectors.js, src/shared/metadata/selectors.test.js
Closes [DHIS2-15329](https://dhis2.atlassian.net/browse/DHIS2-15329)
[DHIS2-15329]: https://dhis2.atlassian.net/browse/DHIS2-15329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: cover remaining metadata selectors

src/data-workspace/section-form/section.js, src/data-workspace/section-form/section.module.css
This PR adjusts the style and placement of the collapsible section control that's introduced in https://github.com/dhis2/aggregate-data-entry-app/pull/390.
=> fix: adjust collapsible control style and placement

.github/workflows/dhis2-verify-app.yml
bumps upload/download artifact versions to keep ci running
=> fix: upload download artifact versions

src/data-workspace/section-form/section.module.css
This PR adjusts the custom title and subtitle text styles.
I've introduced `flex` to allow to limiting the maximum width of the children (for better readability) while still allowing different page alignments.
=> fix: custom text styles

d2.config.js
Implements [DHIS2-18965](https://dhis2.atlassian.net/browse/DHIS2-18965)
[DHIS2-18965]: https://dhis2.atlassian.net/browse/DHIS2-18965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update title in app
