dhis2/aggregate-data-entry-app

src/context-selection/category-option-combo-selector-bar-item/use-category-combination.js, src/context-selection/data-set-selector-bar-item/use-data-set.js, src/context-selection/data-set-selector-bar-item/use-selectable-data-sets.js, src/context-selection/org-unit-selector-bar-item/use-data-set-org-unit-paths.js, src/context-selection/org-unit-selector-bar-item/use-organisation-unit.js, src/context-selection/org-unit-selector-bar-item/use-user-org-units.js, src/context-selection/period-selector-bar-item/use-data-set-period-type.js, src/context-selection/section-filter-selector-bar-item/use-data-set-sections-info.js
This refactors our hooks to use react-query directly, see: https://dhis2.slack.com/archives/C02NHB92S2H/p1640105370054600. The react-query specific code will be replaced by an app-runtime implementation, but since we don't have that yet we're using react-query in the meantime.
Follow-up:
- Set queryProvider defaults (see the defaults in the app-runtime). Things like automatic refresh on network reconnect, cache time, etc.
- Start work on offline functionality, optimistic updates, etc.
Docs:
- https://runtime.dhis2.nu/#/hooks/useDataEngine
- https://react-query.tanstack.com/reference/useQuery
- https://react-query.tanstack.com/guides/query-keys
=> refactor(react-query): move data fetching hooks to react-query

src/data-workspace/data-workspace.js, src/data-workspace/dataset-selector.js
Moving the queries to vanilla react-query so I can use them with the optimistic updates.
=> refactor(queries): move queries to vanilla react-query

src/data-workspace/data-entry-cell/data-entry-cell.js, src/data-workspace/data-workspace.js, src/data-workspace/use-data-value-mutation.js, src/data-workspace/use-mutation-fn.js
- Enabled retry for cell mutations, which will retry in order once online
- Added optimistic updates for cell datavalue mutation
Follow-up:
- Implement optimistic updates for comments
- Cached mutations should only be removed after a server response for that mutation (i.e. success or server error). Otherwise they should persist (check the retry setting)
- Organize the data fetching hooks (so that the query doesn't change without the optimistic update adapting to that change, should probably colocate them)
- Could integrate the isPaused state for the mutation hook
- Keep only the last mutation for each item
- Add a global indicator for the amount of pending mutations
- Persist the query cache with the optimistic updates and the mutation cache
- Ensure that the optimistic updates won't be …
=> feat: retry mutations and optimistic updates

src/data-workspace/data-entry-cell/final-form-wrapper.js
Fixes an issue where refetching `dataValueSet` overwrites optimistically updated values. Also makes it faster to fire sequential mutations!
https://user-images.githubusercontent.com/49666798/150521904-59fa650a-b032-4a04-89f1-b63015102103.mov
=> fix: reinitialize form better

src/data-workspace/data-entry-cell/index.js, src/data-workspace/data-entry-cell/use-data-value-mutation.js, src/data-workspace/data-workspace.js
To prevent our optimistic update from being overwritten by automatic refetches this will disable queries affected by the mutations until all the mutations have settled. This, coupled with final form's https://final-form.org/docs/react-final-form/types/FormProps#keepdirtyonreinitialize should ensure that the optimistic updates remain intact.
https://github.com/tannerlinsley/react-query/discussions/2245#discussioncomment-704718
=> feat: disable datavaluesets query when there are active mutations

i18n/en.pot, src/app/app.js, src/app/mutation-indicator/index.js, src/app/mutation-indicator/mutation-indicator.js
This adds a status indicator for the mutations. Shows the amount of pending mutations if there are any, otherwise will show that all changes have been synced. Placement and styling are just placeholder for now.
=> feat: add mutation status indicator

src/data-workspace/data-entry-cell/use-data-value-mutation.js
This removes the related query invalidation on both success and error. I've left the query disabling when there are pending mutations as that still seems like a good setting to have.
=> fix: remove query invalidation after mutations have settled

src/app/use-query-client.js, src/data-workspace/data-workspace.js
In the spirit of reducing network chattiness, I've disabled `refetchOnWindowFocus`.
It's also mostly because it's annoying to see all the network traffic in the network\-tab when debugging.
We might want to disable `refetchOnReconnect` as well, but that might have some more implications, and it would be interesting to see how that behaves with the optimistic updates.
=> fix(query-client): disable refetch on focus

src/context-selection/org-unit-selector-bar-item/org-unit-selector-bar-item.js, src/context-selection/org-unit-selector-bar-item/use-select-bar-item-value.js
Currently the data set requests contains only the leaf nodes which makes the removed functionality kind of senseless.
Also we agreed to indicate org units that are connected instead of filtering out the ones that are not connected for UX reasons
=> refactor(org unit selector): remove filtering by data set org units

src/app/query-client/use-query-client.js
The existing code works, but I think this approach is better as it only sets the `id` and `params` keys if there are associated values.
=> refactor: only set params and id if present

package.json, src/custom-forms/use-custom-forms.js, src/data-workspace/default-form.js, src/data-workspace/section-form/section.js, src/metadata/selectors.js, src/metadata/selectors.test.js, yarn.lock
This adds memoization to our selectors in a manner that's easy to use with react-query's select, and shares its cache globally. So computations will only run once across the entire app as long as input stays the same. End goal being easy integration of memoization with our data fetching hooks.
Since reselect has a cache size of 1 it won't work with selectors that take parameters like an id. Usage with an id will invalidate the cache for other ids. So I'm using a small wrapper called re-reselect to create a reselect cache per id. Reselect and re-reselect are small. Will add just 2 to 3 kb to the bundle when minified, in total.
I've checked the memoization and currently it breaks only here: https://github.com/dhis2/data-entry-app/blob/development/src/data-workspace/category-combo-table.js#L8 …
=> feat: memoize selectors

i18n/en.pot, src/app/app.js, src/app/layout/layout.js, src/app/layout/layout.module.css, src/app/layout/layout.test.js, src/bottom-bar/bottom-bar.js, src/bottom-bar/bottom-bar.module.css, src/bottom-bar/data-item-bar.js, src/bottom-bar/data-item-bar.module.css, src/bottom-bar/main-tool-bar.js, src/bottom-bar/main-tool-bar.module.css, src/data-workspace/data-entry-cell/entry-field-input.js, src/data-workspace/data-workspace.js, src/data-workspace/data-workspace.module.css, src/metadata/selectors.js, src/metadata/selectors.test.js
Closes [TECH-1210](https://dhis2.atlassian.net/browse/TECH-1210)
* Refactors the layout a little: Puts the footer into the data workspace
* I did this because the app is supposed to display the footer only when rendering a form. The data workspace renders the form conditionally and I didn't want to duplicate the conditions in the footer / app
* Marking @ismay as a reviewer as he's the one who created this part of the app
* Adds the UI + functionality for the "data item bar" (the upper one; only displayed when focusing an item)
* Adds the UI for the "main tool bar", but not the functionality (the lower one; always displayed)
* Marking @KaiVandivier as a reviewer as he's already working on the server side validation which includes the missing functionality in the footer's main tool bar) …
=> feat(footer): add footer UI

src/data-workspace/category-combo-table/category-combo-table.js, src/data-workspace/data-entry-cell/data-entry-field.js, src/data-workspace/data-entry-cell/entry-field-input.js, src/data-workspace/data-entry-cell/inner-wrapper.js, src/data-workspace/data-entry-cell/use-active-cell.js, src/data-workspace/get-field-id.js, src/data-workspace/inputs/boolean-radios.js, src/data-workspace/inputs/file-inputs.js, src/data-workspace/inputs/generic-input.js, src/data-workspace/inputs/long-text.js, src/data-workspace/inputs/option-set.js, src/data-workspace/inputs/true-only-checkbox.js, src/data-workspace/inputs/utils.js, src/data-workspace/section-form/section.js
Adds support for `greyedFields`/disabled-fields. 
This can be activated for `DataSet sections` in the `Maintenance app`. Navigate to list of `Data Sets`, find a section-dataSet -> Hamburger-menu -> Manage sections -> Hamburger Menu in list of Sections -> Manage Grey Fields -> Click field to be disabled. 
Note that there's a backend bug where setting a greyField for a dataElement with `categoryComb` `None/default` results in a 500-error. See [DHIS2-13371](https://jira.dhis2.org/browse/DHIS2-13371).
=> feat: greyed fields

src/app/app-wrapper.js, src/app/app.css, src/app/layout/layout.module.css, src/context-selection/context-selection/right-hand-side-content.js, src/context-selection/options/options.js, src/data-workspace/custom-form/custom-form.module.css, src/data-workspace/data-workspace.js, src/data-workspace/filter-field.js, src/data-workspace/print-area/print-area-context.js, src/data-workspace/print-area/print-area-provider.js, src/data-workspace/section-form/section.js, src/data-workspace/section-form/section.module.css
Add ability to print the currently displayed data set
=> feat: add print support

src/data-workspace/custom-form/custom-form.js, src/data-workspace/custom-form/parse-html-to-react.js, src/data-workspace/custom-form/replace-td-node.js
Code-wise it would have made a lot more sense to replace the input tag, but that caused issues with the table-cell's background color. I couldn't get the content of the `td` to be filled completely, so I ended up with some whitespace inside the `td`. So I did it this way instead, replacing the `td`. Another advantage of this was that I could re-use the `TotalCell` which already came with the right styles.
To test this functionality, I recommend using the EPI Stock dataset.
=> feat(custom-forms): add support for total fields

src/data-workspace/inputs/file-inputs.js, src/data-workspace/use-file-input-url.js, src/data-workspace/use-file-input-url.test.js
adds ability to download uploaded files in file-input control
closes [TECH-1229](https://dhis2.atlassian.net/browse/TECH-1229)
| Before | after |
| ---- | --- |
| <img width="796" alt="image" src="https://user-images.githubusercontent.com/1014725/176493023-c57178c2-315d-4827-a76b-3525d632b236.png"> | ![file-input-link](https://user-images.githubusercontent.com/1014725/176492874-8ad00d71-541c-4944-834f-79b1fbff2f22.gif) |
=> fix: add link to file input control

src/data-workspace/inputs/file-inputs.js, src/data-workspace/inputs/inputs.module.css
Follow-up to #82 
Adds link styles according to [this specification document](https://docs.google.com/document/d/1NDMM-FAGCdM41n8ShnQuS6snvKvdSWNW-rky23cio_I/edit#heading=h.g44lloa2cs97) 🙂
=> fix: style file link according to spec

src/context-selection/contextual-help-sidebar/contextual-help-sidebar.js, src/data-workspace/data-details-sidebar/data-details-sidebar.js, src/right-hand-panel/right-hand-panel.js, src/shared/sidebar/index.js, src/shared/sidebar/sidebar-props.js
Ensure the sidebar for contextual help is displaying without crashing the app
| Before | After |
| --- | -- |
| <img width="833" alt="image" src="https://user-images.githubusercontent.com/1014725/176408919-34b9adf3-7ce2-4617-9933-6a6633b2384a.png"> | <img width="426" alt="image" src="https://user-images.githubusercontent.com/1014725/176408831-999de1fd-53fe-4037-98ab-d0d28255aa59.png"> |
=> fix: enable contextual help side bar

src/data-workspace/category-combo-table/category-combo-table-header.js, src/data-workspace/category-combo-table/category-combo-table.js, src/data-workspace/category-combo-table/data-element-cell.js, src/data-workspace/category-combo-table/padding-cell.js, src/data-workspace/category-combo-table/total-cells.js, src/data-workspace/data-entry-cell/entry-field-input.js, src/data-workspace/section-form/section.js, src/shared/current-item-provider/current-item-context.js, src/shared/current-item-provider/current-item-provider.js, src/shared/current-item-provider/index.js, src/shared/current-item-provider/use-current-item-context.js
Refactors the header in to a separate component. This PR is meant to make the `CategoryComboTable`-component a bit easier to reason about, as well as solve some re-renders.
- useActiveCell caused entire table to re-render
- This is now only re-renders header-component and DataElementCell (header of the data-element)
- CurrentItemContext caused all cells to re-render because they subscribed to this context
- Splitting this to a separate "setter"-context, solves this, as the cells only need to set the item
=> refactor: optimize re-renders

src/data-workspace/data-entry-cell/entry-field-input.js, src/data-workspace/inputs/option-set.js
Note that it seems the old implementation used the wrong `value` for the selected optionSet. From looking at the request from the old `Data Entry`-app, it seems that the `code` is used for the value. This also makes sense, since the user are not allowed to change the `code` after an `option` is created.
=> fix: update optionSet for metadata-api

src/data-workspace/category-combo-table-body/category-combo-table-body.js, src/metadata/selectors.js
Fixes https://dhis2.atlassian.net/browse/TECH-1112 by refactoring the computation to a `cachedSelector`. 
This also moves the `cartesian`-computation to a selector, and thus the options will be stable between components and remounts. So this will only be recomputed once for every `categoryCombo`. Even if that `catComboTable` is unmounted and remounted again.
=> refactor: move sortedcocs-computation to selector

src/app/app-wrapper.js, src/app/app.test.js, src/app/auth/auth-wall.test.js, src/app/layout/layout.test.js, src/data-workspace/data-details-sidebar/audit-log.test.js, src/data-workspace/data-details-sidebar/basic-information.test.js, src/data-workspace/data-details-sidebar/comment.test.js, src/data-workspace/data-details-sidebar/limits.test.js, src/shared/sidebar/title.test.js, src/test-utils/index.js, src/test-utils/render.js
I'm working on updating tests in #73. For this I need the components to be wrapped with the providers that wrapp the app component. @kabaros also had a similar need and ended up with a [`withAppTestWrapper`](https://github.com/dhis2/data-entry-app/blob/19a73e3637/src/test-utils/with-app-test-wrapper.js) HOC.
I already made a comment that I think I'd prefer the [official way](https://testing-library.com/docs/react-testing-library/setup/#custom-render) of doing this, so I created this PR which
* should support @kabaros's case (overriding the Router with `MemoryRouter`)
* exports the `TestWrapper` component as an escape hatch in case tests need to do something special
* updates all existing tests, showing that the changes just work
See …
=> refactor(app wrapper): improve jest test utils

src/bottom-bar/main-tool-bar.js, src/data-workspace/entry-form.js, src/data-workspace/use-close-right-hand-panel-on-selection-change.js, src/right-hand-panel/right-hand-panel.js
- When the right hand panel is open, and the "Run Validation" button in the bottom bar is clicked, then the the panel is toggled closed
- Ensure that the right panel is hidden when the dataset changes
- Get rid of `0` that appeared in comments validation section when no violations exist
**Closing right hand panel when dataset is changed**
| Before | After
| --- | --- |
|  ![close_right_hand_on_change_dataset_before](https://user-images.githubusercontent.com/1014725/182303918-27817f0c-7866-47dd-ab91-81a7f88e3ef7.gif) | ![close_right_hand_on_change_dataset_after](https://user-images.githubusercontent.com/1014725/182303929-3b20eade-7dc9-4ffc-81c1-ea4ee48de3ab.gif) |
**Clicking Run validation in the bottom menu again closes an already open menu**
| Before | After
| --- | --- |
| …
=> fix(validation): tweaks for validation right hand panel

src/data-workspace/indicators-table-body/compute-indicator-value.js, src/data-workspace/indicators-table-body/compute-indicator-value.test.js
The old app used to show `'-'`, but the new app should show nothing.
=> fix: show empty string when indicator value cannot be computed

src/data-workspace/inputs/boolean-radios.js
Issue with clear button not displaying on initial render when there is a boolean value is caused by the clear button component rendering before the values are returned from `form.getFieldState()`. Pulling values/metadata using the useField hook avoids this issue (what I have implemented her). 
Alternately, making the button conditionally render on `fieldState` would work if we wanted to keep using useForm.
=> fix: display radio entry clear button on load if applicable

src/shared/metadata/selectors.js, src/shared/metadata/selectors.test.js
This implements logic for `openPeriodsAfterCoEndDate` which "extends" the endDate of the categoryOption by the number of periods specified by `openPeriodsAfterCoEndDate` (e.g. if categoryOption should expire on `2022-01-15`, but it's being used on a Monthly dataset with `openPeriodsAfterCoEndDate:3`, the categoryOption would effectively expire on `2022-04-15` for the purposes of data entry on that data set)
The logic check for categoryOption already existed in the code (https://github.com/dhis2/data-entry-app/blob/development/src/shared/metadata/selectors.js#L394): `periodEndDate > endDate`, which I have adapted to accommodate for `openPeriodsAfterCoEndDate`
I initially extended the endDate's of the individual categoryOptions, but I switched in the version I am submitting to instead …
=> fix(aoc selector): implement openPeriodsAfterCoEndDate

cypress/integration/context-selection/categories.feature, cypress/integration/context-selection/categories/index.js, src/context-selection/attribute-option-combo-selector-bar-item/attribute-option-combo-selector-bar-item.js, src/context-selection/attribute-option-combo-selector-bar-item/categories-menu.js, src/context-selection/attribute-option-combo-selector-bar-item/categories-menu.module.css, src/context-selection/attribute-option-combo-selector-bar-item/use-should-component-render-null.js, src/data-workspace/data-workspace.js, src/data-workspace/data-workspace.module.css, src/shared/metadata/selectors.js, src/shared/metadata/selectors.test.js, src/shared/use-context-selection/use-manage-inter-param-dependencies.js
This PR restricts the selectable attribute options based on the organisation units assigned to the underlying category option.
Additionally, it updates the UI (as discussed on the ticket https://dhis2.atlassian.net/browse/TECH-1326), to communicate when form cannot be selected because no valid attribute options exist for the select organisation unit/period.
=> fix: restrict att opts by org unit

src/data-workspace/data-details-sidebar/limits-form-wrapper.js, src/data-workspace/data-details-sidebar/update-limits.js, src/data-workspace/inputs/index.js, src/data-workspace/inputs/validators.js, src/data-workspace/min-max-limits-mutations/use-delete-limits.js, src/data-workspace/min-max-limits-mutations/use-update-limits.js
This fixes the issue where zeros, negatives, decimal values could not be entered (even when valid): https://dhis2.atlassian.net/browse/TECH-1327
I noticed the save button was clickable when there were errors (but no post request was sent), so I have disabled it when there are errors
=> fix(min/max validators): allow entry of zero,decimals,negatives

src/data-workspace/data-details-sidebar/history.js, src/data-workspace/data-details-sidebar/history.module.css
Adds a 'No history' message in the same style as the other details sidebar item with no values.
I think it's a bit silly to add a style sheet for this one class, but I thought this was most in line with what we're doing in this section of the code.
=> fix(history): add comment for no history ui

src/data-workspace/data-workspace.js, src/data-workspace/final-form-wrapper.js, src/shared/use-context-selection/use-context-selection.js
This prevents re-render of the entire form when a `dataValue` is updated.
From my limited testing this does not seem to cause any new issues. But it's worth testing more.
=> fix(final-form-wrapper): stable initialValues

src/app/query-client/configured-query-client-provider.js, src/shared/highlighted-field/use-highlighted-field.js, src/shared/use-data-value-set/use-data-value-set.js
[TECH-1320](https://dhis2.atlassian.net/browse/TECH-1320)
This also fixes persisted queries. Previously, they would only be retrieved from  the cache "every other reload of the app", because the `meta`-property on the query was not persisted - so just hydrate queries would not be persisted again, due to lacking `meta.persist`. This should now be fixed by adding this property to all dehydrated queries.
=> fix: data values duplicate request

src/data-workspace/validation/validation-comments-violations.js, src/data-workspace/validation/validation-results-sidebar.js
- turns off escaping of data element short names in comment violation errors ([TECH-1331](https://dhis2.atlassian.net/browse/TECH-1331))
- hides `No validation alerts for this data` text if there are comment violations ([TECH-1330](https://dhis2.atlassian.net/browse/TECH-1330))
=> fix(validation sidebar): clean up validation sidebar

src/context-selection/contextual-help-sidebar/shortcuts.js
This removes reference to double clicking to open data details. See decisions on ticket: https://dhis2.atlassian.net/browse/TECH-1291
=> fix(help sidebar): remove double click text [TECH-1291]

src/app/query-client/configured-query-client-provider.js, src/app/query-client/use-query-client.js, src/data-workspace/data-entry-cell/inner-wrapper.js, src/data-workspace/data-value-mutations/data-value-mutations.js, src/data-workspace/data-value-mutations/index.js, src/data-workspace/data-value-mutations/mutation-functions.js, src/data-workspace/data-value-mutations/mutation-key-factory.js
[TECH-1356](https://dhis2.atlassian.net/browse/TECH-1394)
Also fixes [TECH-1393](https://dhis2.atlassian.net/browse/TECH-1393)
We didn't `resumePausedMutations` after they were hydrated from the store, so we lost those values after the user reloaded the app and went online again.
This needed some additional changes, because the mutations are now not necessarily mounted - and thus each mutation needs a `mutationDefault` - that describes how to send that stored mutation (since the `mutateFn` themselves are not stored/serialized). 
One complication of that, is that the `mutateFn` did not have access to the `queryKey` (only the `variables` passed to mutate!). Which would make it so we would have to include the mutationKey params to all the variable-objects. However, after digging around I …
=> fix: resume queries when reloading app

src/bottom-bar/main-tool-bar.js, src/data-workspace/entry-form.js, src/shared/stores/entry-form-store.js, src/shared/stores/index.js
Fixes [TECH-1405](https://dhis2.atlassian.net/browse/TECH-1405)
Pretty simple implementation, with a entryForm zustand-store. Another approach would be to share the `form`-ref in a context, like @HendrikThePendric proposed earlier. Or we could just put it in the same zustand-store. Not sure what you think is best. 
Sharing form-ref could be beneficial if we eg. want to focus the first errored-field when the user clicks on the "Invalid"-icon or something?
=> feat(bottom-bar): count number of form-errors

.gitignore, src/app/app-wrapper.js
React Query dev tools are now **disabled** by default. If you set the `REACT_APP_ENABLE_RQ_DEVTOOLS`env variable to true, they will be **enabled**:
To have them temporarely enabled, it is recommended to start the app like this:
```bash
REACT_APP_ENABLE_RQ_DEVTOOLS=true yarn start
```
To have them permanently enabled, please add the following line to a `.env.development.local` file:
```bash
REACT_APP_ENABLE_RQ_DEVTOOLS=true
```
=> chore: conditionally render devtools and ignore local env files

src/app/app-wrapper.js, src/app/query-client/configured-query-client-provider.js, src/data-workspace/data-value-mutations/mutation-functions.js, src/shared/use-data-value-set/use-data-value-set.js
Fixes a regression in #159 .
DataValues would be fetched before mutations are sent if doing this:
Go Offline -> Edit values -> reload app -> Go online.
This can cause problems, since the cache would update with the old values from the server, and not update again after.
This is basically doing the same thing as before that fix - but now we are using the `queryClient.isMutating` - which won't subscribe and re-render the hook, and thus prevent fetching after every value-change.
Also the order of `setMutationDefaults` seem to matter, so it seems that `mutationKeys.file()` must be applied before the more generic `update()`, or else the file would be sent with the `update()`-mutationObject.
=> fix: fix some offline issues

src/shared/stores/data-value-store.js
Fixes [Tech-1424](https://dhis2.atlassian.net/browse/TECH-1424)
Might've been introduced in a bad merge-conflict, but we were using the wrong parameter-name.
=> fix(comment-indicator): use correct parameter

src/data-workspace/data-entry-cell/data-entry-cell.module.css
Fixes some styling issues with highlighted field. Previously, the `!important` keyword on highlighted-field prevented `invalid` and `synced` styles from being applied to the highlighted field when this was unfocused.
I think we want the `white`-background when editing the field - and this is now done by using the `.active`-selector, which is in my opinion more correct than using the `highlighted-field`-selector.
Highlighted-synced unfocused:
Before: 
Highlighted-synced focused:
(same as before)
Highlighted-error unfocused:
Before:
=> fix: highlighted cell synced background

src/data-workspace/data-details-sidebar/limits-form-wrapper.js, src/data-workspace/data-details-sidebar/limits-input.js, src/data-workspace/data-details-sidebar/limits-validation-error-message.js, src/data-workspace/data-details-sidebar/update-limits.js
~~Adds a `touched`-check for validation so that the error-message does not show up before they have the user has a chance to prevent the error.~~
Errors are now hidden until the user has clicked "Save limits", and only shown if this fails. This is to prevent validation message showing up before user has a chance to prevent the error. After the first time submission fails, the validation will work like before. This is to make the error-message response once an error has occurred. 
I've enabled the `Save Limits`-button to prevent confusion, where the `Save limits`-button was disabled without an error message. Error message will show and stop submitting (updating minmax) if no valid limits.
I was also a bit confused about the bi-directional `'A min is required when providing a max` for both …
=> fix(update-min-max): only show error message after submit failed

cypress/integration/context-selection/section-filter/index.js, src/bottom-bar/data-item-bar.js, src/bottom-bar/main-tool-bar.js, src/bottom-bar/main-tool-bar.module.css, src/context-selection/section-filter-selector-bar-item/section-filter-selector-bar-item.js, src/data-workspace/custom-form/custom-form.module.css, src/data-workspace/data-details-sidebar/basic-information.js, src/data-workspace/data-details-sidebar/basic-information.test.js, src/data-workspace/data-entry-cell/data-entry-cell.module.css, src/data-workspace/data-workspace.js, src/data-workspace/data-workspace.module.css, src/data-workspace/table-body.module.css, src/shared/highlighted-field/use-highlighted-field.js
This adds categoryOptionCombo information to the sidebar, uses categoryOptionCombo.displayName consistent with the old app, and rearranges dataElement.description to top of sidebar (see ticket for details)
_before_
_after_
This harmonizes/corrects the styling for default form padding cells/section form non-allowed cells (grey fields)/custom form empty cells. See ticket for more details.
Examples below comparing locked against custom form empty cells before and after.
_before_
_after_
This moves the position of the synced indicator (see discussions on ticket; Lars and Phil objected to the original floating positioning)
_before_
_after_
This updates "Show all sections" to "All sections" (as requested by Lars)
_before_
_after_
=> fix: update miscellaneous design issues

src/data-workspace/data-workspace.js, src/data-workspace/query-key-factory.js, src/shared/use-data-value-set/use-data-value-set.js
Sorry for these back-and-forth fixes for refetching. I thought I had fixed this by not "subscribing" with `useIsMutating`-hook. But apparently if the subscribed field re-renders in the meantime between fetches - it will refetch all dataValues again. This could happen if you changed a field, then highlighted another field quickly. 
I've set the `staleTime: infinity` to have more control over refetches. Now we manually refetch whenever the form selection changes. 
Also simplified `refetchOnMount`, because this is not needed anymore due to our manual `invalidateQueries`.
=> fix(data-value-set): refetch only when changing context-selection

package.json, src/data-workspace/data-entry-cell/data-entry-field.js, src/data-workspace/data-entry-cell/entry-field-input.js, src/data-workspace/data-entry-cell/inner-wrapper.js, src/data-workspace/final-form-wrapper.js, src/data-workspace/inputs/boolean-radios.js, src/data-workspace/inputs/file-inputs.js, src/data-workspace/inputs/generic-input.js, src/data-workspace/inputs/long-text.js, src/data-workspace/inputs/option-set.js, src/data-workspace/inputs/true-only-checkbox.js, src/data-workspace/inputs/utils.js, yarn.lock
I've moved the `syncStatus` to use react-final-form `mutator`, and instead of manually setting `synced: true`, we're calculating the `syncStatus` based on the `lastSyncedValue`. 
It can be argued whether it's necessary to have `lastSyncedValue` in the `meta.data` using `mutators` - since we could've just used the previous `setSyncStatus`. But this sets up the wiring required for setting `syncErrors` as well, and we might as well gather these in the `meta.data`. Also means that we can cleanup the deep passing of the `syncStatus` and `setSyncStatus`.
=> fix: clear sync-status when value changes

i18n/en.pot, src/app/load-app.js, src/data-workspace/data-details-sidebar/basic-information-follow-up-button.js, src/data-workspace/data-details-sidebar/comment.js, src/data-workspace/data-details-sidebar/comment.test.js, src/data-workspace/data-details-sidebar/limits-delete-button.js, src/data-workspace/data-details-sidebar/limits-display.js, src/data-workspace/data-details-sidebar/limits.test.js, src/data-workspace/data-details-sidebar/no-limits.js, src/data-workspace/entry-form.js, src/shared/locked-status/locked-info-provider.js, src/shared/locked-status/locked-states.js, src/shared/use-current-date-string-at-server-timezone/use-current-date-string-at-server-timezone.js, src/shared/use-user-info/index.js, src/shared/use-user-info/use-can-user-edit-fields.js, src/shared/use-user-info/user-info-selectors.js
Closes TECH-1439 ([link](https://dhis2.atlassian.net/browse/TECH-1439))
NOTE: @HendrikThePendric commented on the tooltip issue. We've agreed to tackle that separately as it's already tracked in [TECH-1341](https://dhis2.atlassian.net/browse/TECH-1341) and it's not a new issue of this PR.
=> feat: respect F_DATAVALUE_ADD user authority

src/bottom-bar/complete-button.js, src/bottom-bar/main-tool-bar.js, src/context-selection/contextual-help-sidebar/shortcuts.js, src/context-selection/contextual-help-sidebar/shortcuts.module.css, src/data-workspace/data-details-sidebar/no-limits.js, src/data-workspace/data-details-sidebar/no-limits.module.css, src/data-workspace/data-entry-cell/validation-tooltip.js
_before_
_after_
_before_
_after_
_before_
_after_
I think @Birkbjo is including a fix for this in his PR for error handling, but I thought maybe it would be sensible to submit separately as well, so that there's a fix independent of those changes?
_before_
_after_
=> fix: fix design issues from testing

src/shared/locked-status/use-check-lock-status.js
fixes variable name to make sure data input periods trigger locking:
_after PR (with data input period added to Facility Assessment for 2019_:
=> fix: update variable name [TECH-1465]

src/shared/data-value-mutations/use-data-value-params.js, src/shared/use-api-attribute-params.js
These were not stable, and thus the result of these hooks were unfit for use in other hooks, as that would cause them to run on every-render.
=> fix: make useDataValueParams and useApiAttributeParams stable

.github/renovate.json
This enables automerging minor (and patch) updates to our default branch (development). This will happen without any input from us, outside of oslo office hours. It will create a PR and require all status checks to pass before it merges.
Major updates still need to be triggered and merged manually by us.
- https://docs.renovatebot.com/key-concepts/automerge/
- https://docs.renovatebot.com/key-concepts/dashboard/#require-approval-for-major-updates
- https://docs.renovatebot.com/presets-default/#automergepr
- https://docs.renovatebot.com/presets-default/#automergeminor
- https://docs.renovatebot.com/presets-default/#automergerequireallstatuschecks
- https://docs.renovatebot.com/presets-schedule/#schedulenonofficehours
- https://docs.renovatebot.com/presets-npm/#npmunpublishsafe
- …
=> ci(renovate): enable automerging minor updates

.github/renovate.json
The automerging seems to work well. Some manual intervention required at times, but it seems stable enough to enable this to run outside of office hours.
=> ci(renovate): schedule updates outside of office hours

.github/renovate.json
Move to our shared renovate config. Hosted here: https://github.com/dhis2/renovate-config
=> ci(renovate): use our shared renovate config

src/context-selection/org-unit-selector-bar-item/org-unit-selector-bar-item.js, src/context-selection/org-unit-selector-bar-item/org-unit-selector-bar-item.module.css
Fixes [UX-110](https://dhis2.atlassian.net/browse/UX-110).
This PR changes the style of disabled (not available for selection) org units in the org unit selector:
- Icons are removed,
- Tooltip is shown on hover,
- Icon "legend" at bottom of menu removed,
A small change is made to the menu itself:
- Menu design is changed to remove margin around all content.
Note: the tooltip reuses the available i18n label `Dataset is not assigned to this organisation unit`, even though the label _should_ use `Data set` in two words, but it didn't seem worth the i18n change.
[UX-110]: https://dhis2.atlassian.net/browse/UX-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: adjust disabled org unit style

src/app/load-app.js
Previously, the app would crash without a helpful error message
Before:
After:
=> fix: metadata and user info error handling

src/app/app.css, src/data-workspace/category-combo-table-body/total-cells.js
Totals were rendered when selecting "Print empty form". This small PR adds the `.total-cell`-selector to also hide total values when a form is printed with empty values.
=> fix(total-cell): clear total value when printing empty form

src/shared/completion/use-set-form-completion-mutation.js, src/shared/use-data-value-set/query-key-factory.js
Fixes the completion for data sets with attribute combos.
Note the backend requires attribute options in an array of options (I'd think it might be better for the backend to accept a concatenated string of these options, i.e. `cp:someUID0001;someUID0002;someUID0003` so that it matches the request format for dataValues post, but I don't think it's worth it to request a change as part of this fix)
*before*
=> fix: include attribute options in completion post [DHIS2-15032]

src/shared/api-errors/api-mutation-error.js
Note: this error only occurred in production. The minified code does not guarantee that error.constructor.name == FetchError.name, and hence the errors are not being saved to the zustand store (e.g. see https://github.com/dhis2/aggregate-data-entry-app/blob/cf3e542e4dfdd10e6438ad33c3f0c4bc12f3beae/src/shared/data-value-mutations/data-value-mutations.js#L64-L71)
**Before**
**After**
=> fix: use FetchError class from app-runtime [DHIS2-15085]

src/shared/completion/use-set-form-completion-mutation.js
fixes rollback of unsuccessful data set completion.
Note the function signature for tanstack-query onError callback: `onError: (err: TError, variables: TVariables, context?: TContext) => Promise<unknown> | unknown`
=> fix: rollback failed complete [DHIS2-15033]

src/context-selection/period-selector-bar-item/use-date-limit.js, src/context-selection/period-selector-bar-item/use-periods.js
Noticed when looking at a radom app with rtl direction, but when I tried to select data set with language set to Arabic, the app crashed.
Turns out that the moment locale when set to `ar` formats the dates with Arabic numerals, e.g. so a date like `2022-12-03T12:00:00.000` when formatted in yyyy-MM-DD would produce this: `٢٠٢٢-١٢-٠٣`, which would not be interpretable by the various period generation functions we had and hence the app would crash (invalid date was passed).
Note: the moment/Arabic numeral format is still being used in the audits, but this does not cause any issues:
=> fix: prevent moment from using arabic numerals for dates [DHIS2-15277]

.github/workflows/dhis2-verify-app.yml, cypress.config.js, cypress/support/e2e.js, package.json, yarn.lock
Cypress test results are now published to Reportportal:
The idea is to have all our test results in one place. so there will be a second PR to send the jest test results. And a third one to add more meta-data at the tests level, this will help on getting more insights from the reportportal dashboard
=> test: publish cypress test results to reportportal

src/shared/date/use-server-time-offset.js, src/shared/date/use-server-time-offset.test.js
This PR addresses an immediate issue where the data entry app is crashing when the `serverTimeZoneId` returned from api/system/info. In the case reported by user, the serverTimeZoneId was `GMT+08:00` instead of the equivalent IANA database format (`Etc/GMT-8`), which is expected by javascript. Bug report is [DHIS2-15511](https://dhis2.atlassian.net/browse/DHIS2-15511)
FYI. There's a much longer discussion on the related ticket [DHIS2-15361](https://dhis2.atlassian.net/browse/DHIS2-15361) about why this is occurring, which could then inform how we generally want to handle this on the front end going forward. For now, this PR just prevents the app from crashing in the case (and then assumes no client/server time zone difference, thus letting backend enforce any time boundaries). Note that …
=> fix: handle non-standard server time zone ids [DHIS2-15511]

src/data-workspace/custom-form/replace-td-node.js, src/data-workspace/indicators-table-body/compute-indicator-value.js, src/data-workspace/indicators-table-body/compute-indicator-value.test.js, src/data-workspace/indicators-table-body/indicator-table-cell.js, src/data-workspace/indicators-table-body/indicators-table-body.js, src/data-workspace/indicators-table-body/use-indicator-value.js
This adds functionality to round indicators if they have decimals specified for their output.
**Before**
**After**
Note: when I looked at the legacy data entry app seems to just round to 1 decimal if decimals were specified (and did not follow the actual number of decimals specified). I assume we don't want to do that. I checked against how the decimals were displaying in visualizer and tried to be consistent with that:
visualizer app is also not add trailing 0s if indicator has more specified decimals than necessary (e.g. if the indicator is 2/4 and it has 5 decimals specified, it will only display as .5 and not as .50000, so I have not added any trailing 0s for the data entry app)
=> fix: handle indicator decimals [DHIS2-15631]

.github/workflows/dhis2-verify-app.yml, cypress.config.js, jest.config.js, package.json, yarn.lock
After the previous PR that sends Cypress test results to the ReportPortal dashboard (https://github.com/dhis2/aggregate-data-entry-app/pull/349),
This second PR sends now Jest test results to ReportPortal:
=> test: publish jest test results to reportportal

i18n/en.pot, src/context-selection/period-selector-bar-item/period-menu.js, src/context-selection/period-selector-bar-item/period-menu.module.css
See ticket: https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-14444
Adds a message when there are no periods that are selectable in the current year:
Joe approved the design / message over slack.
=> fix: add message when year has no periods [DHIS2-14444]

src/data-workspace/indicators-table-body/indicators-table-body.js, src/data-workspace/indicators-table-body/indicators-table-body.test.js, src/data-workspace/section-form/section.js
See ticket: https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-15883
This fixes an issue where the section would error out (and would crash) if a section had no data elements present. The problem was that the IndicatorTableBody component has logic that adds padding cells based on the number of data elements; when no data elements were present, the calculation was saying that the data elements in the section had -Infinity maxColumnsInSection)
** I also noticed that there was a problem adjusting the padding cells based on the totals being displayed. We were removing a padding cell when column totals were displayed (if you sum up by column, you get an additional row) and not when row totals were displayed (when you sum up by row, you get an additional column). 
An …
=> fix: handle sections without data elements [DHIS2-15883]

jest.config.js
After report-portal was added, it was run even if the required environment-variables wasn't configured. This causes a lot of verbose logging and error-messages in the console.
Not sure if this is the best way, but I couldn't find any native way to do this in `agent-js-jest`. I'm a bit surprised the tool is actually running even if these variables are not defined.
We might want a different `jest.config` for CI and local testing instead?
=> chore(report-portal): run reports only when env is setup

src/context-selection/contextual-help-sidebar/cell.js, src/context-selection/contextual-help-sidebar/cell.module.css, src/context-selection/contextual-help-sidebar/cells-legend.js, src/data-workspace/data-entry-cell/data-entry-cell.module.css, src/data-workspace/data-entry-cell/inner-wrapper.js, src/data-workspace/data-entry-cell/validation-tooltip.js, src/data-workspace/inputs/generic-input.js, src/data-workspace/inputs/validators.js, src/data-workspace/inputs/validators.test.js, src/shared/stores/entry-form-store.js
https://dhis2.atlassian.net/browse/DHIS2-16284
Requested by Olav on slack. Previously min-max limits were implemented as "hard" limits, and thus the values would not be saved if the value was outside of the limit.
Context from Olav:
> I think this is problematic and should be changed:
min-max are generally defined as some statistical thresholds, so we have to expect that correct values could be outside the thresholds from time to time
data is typically entered from a paper form. It’s good that suspcious values are flagged, but it’s problematic if the data entry user is not able to enter “official” numbers written on the reporting forms
its inconsistent with how validation rules work: flagging issues, but allowing them to be saved
it looks like if a value has previously been entered in a …
=> fix(validator): limits as warning instead of error

src/data-workspace/entry-form.js
While working on https://github.com/dhis2/aggregate-data-entry-app/pull/357 , I noticed the entire form was being re-rendered on each input. We've spent quite a lot of time to optimize this, but I realized it only happened when the form contained an error. The culprit was the logic to keep the zustand-store up to date with the form-errors. I've now moved this to its own component, so the hook won't re-render the entire form. 
Before: 
https://github.com/dhis2/aggregate-data-entry-app/assets/13852438/16cd515e-11a8-4693-b457-c8b36f27ecc0
After:
https://github.com/dhis2/aggregate-data-entry-app/assets/13852438/3e314895-5a0d-4394-8fde-b7e38332ed00
=> fix: prevent unnecessary renders when form has errors

src/data-workspace/inputs/validators.js, src/shared/validation/index.js, src/shared/validation/is-integer.js
Fixes [DHIS2-14075](https://dhis2.atlassian.net/browse/DHIS2-14075)
Doc comment from `is-integer.js`:
```/**
* The `integer` validator of the `@dhis2/ui` library uses
* `Number.isSafeInterger` to assess whether it the value is a valid integer or
* not. The range allowed by that methid is -(2^53 - 1) to 2^53 - 1.
*
* The `isInteger` validator in the Java core uses the `isValid` method of
* apache's `IntegerValidator` class (see
* `dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/util/MathUtils.java`),
* which allows an integer range from
* -2147483648 to 2147483647.
*
* This validator re-uses `@dhis2/ui`'s validator but restricts the integer to
* the range allowed by the Java core.
*/```
[DHIS2-14075]: https://dhis2.atlassian.net/browse/DHIS2-14075?atlOrigin=eyJpIj …
=> fix(integer validation): limit range to the accepted range of the dhis2-core

src/context-selection/period-selector-bar-item/use-date-limit.js, src/context-selection/period-selector-bar-item/use-date-limit.test.js
Fixes an issue with calculate on dateLimit. Dates from periods are returned in yyyy-mm-dd format, which when passed to Date() constructor will assume that the time is UTC and return a corresponding time zone for the browser time zone. E.g. if you are in Guatemala, `2024-01-01` becomes `2024-12-31T18:00:00`
This adds an extra function in useDateLimit to initialize with Date(yyyy,mm-1,dd) so that the date is initialized based on local time zone (not UTC).
I added a couple of basic tests for the function, but to test more we'd need to fake the system time zone.
=> fix: adjust time zone for dateLimit [DHIS2-16470]

src/data-workspace/section-form/section-description.js
`underline` html tag is [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u), and we should accept `u` instead for text before and after.
Documentation updated in https://github.com/dhis2/dhis2-docs/pull/1366 
fixes bug related to https://dhis2.atlassian.net/browse/DHIS2-17002
=> fix(DHIS2-17002): accept 'u' html tag instead of 'underline'

src/data-workspace/section-form/displayOptions.js, src/data-workspace/section-form/section.js
Fixes a bug where the app would crash if used on a server version where `section.displayOptions` are not present. 
We could've just checked for the presence before parsing, but I wrapped `JSON.parse` in a try-catch, because `displayOptions` is just an arbitrary string - so it could fail in various ways.
We also should introduce some error-boundaries to the app, so the entire app doesn't crash on errors like this.
=> fix(section-form): prevent crash when displayOptions are not present

.github/workflows/dhis2-verify-app.yml, README.md, cypress/support/generateTestMatrix.js
**Conditional Recording Triggers**: Implemented conditional recording triggers via commit messages and GitHub labels to ensure that Cypress tests are only recorded when necessary.
**Parallel Execution Strategies**: Refined parallel execution strategies to improve efficiency and resolve test redundancies in GitHub Actions.
**Debugging Enhancements**: Added detailed debugging outputs to help track the dynamic values of the test environment variables and ensure correct parameter passing in the workflow.
**Update Documentation**: Updated the documentation to reflect the changes and ensure clarity on the new CI/CD processes.
**Reduced Cypress Cloud Credit Usage**: By optimising the conditions under which tests are recorded and uploaded to Cypress Cloud, we anticipate a significant reduction in …
=> chore: [DHIS2-17458] enhance CI 

src/data-workspace/data-entry-cell/entry-field-input.js, src/data-workspace/inputs/date-input.js, src/data-workspace/inputs/date-input.test.js, src/data-workspace/inputs/generic-input.js, src/data-workspace/inputs/index.js, src/data-workspace/inputs/inputs.module.css
Fixes [DHIS2-17446](https://dhis2.atlassian.net/browse/DHIS2-17446)
-----
**Description:**
- Using the Calendar Input component from the UI library that has support for multi calendars. 
**Tasks**
**Screenshot**
1. iso8601
[DHIS2-17446]: https://dhis2.atlassian.net/browse/DHIS2-17446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add support for multi calendar dates

src/data-workspace/category-combo-table-body-pivoted/category-combo-table-body-pivoted.js, src/data-workspace/category-combo-table-body/category-combo-table-body.js, src/data-workspace/section-form/displayOptions.js, src/data-workspace/section-form/section-form.js, src/data-workspace/section-form/section.js, src/data-workspace/section-form/section.module.css, src/data-workspace/table-body.module.css, src/data-workspace/use-feature.js
Implements [DHIS2-17507](https://dhis2.atlassian.net/browse/DHIS2-17507).
This PR allows for sections of a data set to be collapsible
We have decided that all sections should be collapsible by default, and this for now will not be a setting in the maintenance app 
Collapsible is applied only when the  " render as tabs" option is not turned on for the specific dataset
We are aiming to add more form configuration options as part of an initiative to provide configurations natively to data entry forms to reduce the necessity for custom forms. Users are currently building custom forms as a workaround for shortcomings of the configuration options (ability to transpose, or customise a cell design) or implementation (such to avoid issues with RTL issues).
This is [an …
=> feat: make data sets sections collapsable

src/data-workspace/section-form/sanitized-text.js, src/data-workspace/section-form/section-form.js, src/data-workspace/section-form/section.js, src/data-workspace/section-form/section.module.css
Implements [DHIS2-18129](https://dhis2.atlassian.net/browse//DHIS2-18129).
This PR allows users to add a title/ substitle to datasets
The displayOptions was added as a JSON type in the BE to allow us flexibility to add more options without updating the back-end. See discussion in https://github.com/dhis2/dhis2-core/pull/16562
We are aiming to add more form configuration options as part of an initiative to provide configurations natively to data entry forms to reduce the necessity for custom forms. Users are currently building custom forms as a workaround for shortcomings of the configuration options (ability to transpose, or customise a cell design) or implementation (such to avoid issues with RTL issues).
This is [an RFC](https://dhis2.atlassian.net/wiki/spaces/SOFTWARE/pages/121995265/Fo …
=> feat: add title and subtitle to data sets if set in display options

cypress/e2e/context-selection/section-filter/index.js, src/context-selection/section-filter-selector-bar-item/section-filter-selector-bar-item.js
This Pr is meant to address the performance problems that occur when forms with many fields are rendered.
In this PR, we mitigate the problem by rendering by default only one section. This is a temporary fix until a proper fix will be in place.
=> feat: when we have multiple sections, default to first section 

i18n/en.pot, src/bottom-bar/complete-button.test.js, src/bottom-bar/use-on-complete-callback.js, src/context-selection/contextual-help-sidebar/cell.js, src/context-selection/contextual-help-sidebar/cell.module.css, src/context-selection/contextual-help-sidebar/cells-legend.js, src/data-workspace/category-combo-table-body/category-combo-table-body.test.js, src/data-workspace/data-entry-cell/data-entry-cell.module.css, src/data-workspace/data-entry-cell/inner-wrapper.js, src/data-workspace/data-workspace.js, src/shared/completion/use-imperative-cancel-completion-mutation.js, src/shared/index.js, src/shared/metadata/selectors.js, src/shared/stores/entry-form-store.js, src/shared/use-is-compulsory-data-element-operand.js, src/shared/validation/index.js, src/shared/validation/use-imperative-validate.js, src/shared/validation/use-imperative-validate.test.js
This PR addresses the referenced ticket ([DHIS2-17647](https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-17647)) and in general
(Note when I was testing this, I just made a couple of new data elements and assigned them to a new data set and then marked some as compulsory data element operands)
**Before:**
- no handling of compulsory data element operands
**After:**
- compulsory data element operands are marked with an `*` when they are empty. They then will get other applicable styling as values are entered (e.g. synced, error, warning)
- if the data set has `compulsoryFieldsCompleteOnly: true` ("Complete allowed only if compulsory fields are filled in" in the maintenance app), a snack bar message will appear saying that the form cannot be completed due to compulsory …
=> fix: handle compulsory data element operands [DHIS2-17647]

src/context-selection/attribute-option-combo-selector-bar-item/attribute-option-combo-selector-bar-item.js, src/shared/metadata/selectors.js, src/shared/metadata/selectors.test.js, src/shared/use-context-selection/use-manage-inter-param-dependencies.js
See the ticket https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-18526
(Note the ticket has some metadata that can be imported for testing purposes)
We need to get orgUnit.path to be able to check if an attribute option is assigned to an ancestor of the selected organisation unit and to determine if that attribute option should be selectable. 
We can get this with the existing hook/query `useOrgUnit`, though it is not available offline. We've decided (see ticket) that we will not modify the UI in case we are offline. When offline, we will thus check against the selected org unit only (not its ancestors), so the available options could be incomplete, but we will consider this enough of an edge case not to modify the UI for this.
I've manually tested with the metadata …
=> fix: test ancestor orgunits for aoc assignment [DHIS2-18526]

i18n/en.pot, src/bottom-bar/validation-results-sidebar/validation-results-sidebar.test.js, src/data-workspace/indicators-table-body/compute-indicator-value.js, src/data-workspace/indicators-table-body/compute-indicator-value.test.js, src/data-workspace/indicators-table-body/indicator-table-cell.js, src/data-workspace/indicators-table-body/indicator-table-cell.test.js, src/data-workspace/table-body.module.css
See https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-14221, including notes.
This changes the presentation of indicators where the calculation is invalid. Previously, we showed either blank or '0' if the expression came back as invalid. This change updates to show
1. For expressions that cannot generally be calculated client-side (e.g. periodOffset):
InfoIcon / Tooltip that says `This value cannot be calculated in this app`
2. For expressions that cannot be calculated because they evaluate to NaN/Infinity (e.g. 1/0):
WarningIcon / Tooltip that says `This expression is not mathematically calculable {{numeratorValue}}/{{denominatorValue}}`
**Testing**
- I've manually tested by creating an indicator with periodOffset (I think this is only out-of-the-box expression in …
=> fix: add warning about noncalculable indicators [DHIS2-14221]

src/data-workspace/custom-form/custom-form.module.css, src/data-workspace/data-workspace.module.css
This is a fix for https://dhis2.atlassian.net/browse/BETA-362 (replicated by https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-19400)
I have, to be honest, not looked in much detail about why the auto width is not appropriately getting the size of this form, but it seems like it should be fine to explicitly set width: 100% on these containers in any case.
**Before:**
**After:**
=> fix: custom form styling [BETA-362]

src/shared/metadata/selectors.js, src/shared/metadata/selectors.test.js
see https://dhis2.atlassian.net/browse/DHIS2-19523
This fixes the case where a user does not have access to certain individual attribute options associated with a attribute (this can happen when user does not have sharing for the specific attribute).
**Testing**
You can test this with admin user (by following instructions on ticket) or by unsharing a partner option and then opening 'ART Monthly Summary' data set.
I've also added an automated test to confirm that undefined options get sorted out.
=> fix: prevent crash with missing category options [DHIS2-19523]

src/data-workspace/category-combo-table-body/category-combo-table-body-header.js, src/data-workspace/category-combo-table-body/category-combo-table-body.js, src/data-workspace/category-combo-table-body/category-combo-table-body.test.js, src/data-workspace/custom-form/custom-form.module.css, src/data-workspace/data-workspace.module.css
See https://dhis2.atlassian.net/browse/DHIS2-18640.
This ticket removes row/column totals if data element is of a non-numeric type (such that the total cannot be calculated).
**Before**
**After**
_note: if there is a mix of numeric and non-numeric value types, the row totals (but not column totals) will display_
**Testing:**
tested manually plus added some manual tests
=> fix: number only totals [DHIS2-18640]

src/data-workspace/custom-form/parse-html-to-react.test.js, src/data-workspace/custom-form/replace-input-node.js
See: https://dhis2.atlassian.net/browse/DHIS2-19768
This disables cells marked with disabled property in custom forms.
**Before**
**After**
Testing
I added some basic automated tests (just testing if DataEntryField gets disabled prop based on the original html)
_Sample metadata for manual testing_
You can metadata import this through import/export app on SL database, and then go to `00 - test - disabled` data set in data entry app:
[custom_form_disabled_fields.json](https://github.com/user-attachments/files/20868150/custom_form_disabled_fields.json)
=> fix: disabled fields in custom forms [DHIS2-19768]

i18n/en.pot, src/data-workspace/data-details-sidebar/audit-log.jsx, src/data-workspace/data-details-sidebar/audit-log.test.jsx
This fixes an issue with audits. New updated audit log from backend is not returning a value for DELETED audit items. We expected a value, and we showed the crossed out value.
This PR updates the logic to show the tag with text "Deleted" in cause the deleted audit item does not have a value
Note: I've left handling in case there is a value because older versions have that and we might add this back on the backend (pending discussion)
=> fix: deleted audit no value
